### ISSUE TITLE
In page summary using ChatGPT API

### ISSUE THREAD

**Issue by royhadad** [kazuki-sf/YouTube_Summary_with_ChatGPT#3]
This extension is awesome, and I've been thinking.
What if a server received the transcript automatically, accessed the chatGPT API, and returned the summary to be shown **inside** of the extension window.
the summaries can also be cached so every youtube video is only summarized once.

did you consider it?

**Comment by robertciotoiu** [comment]
ChatGPT API is not free to access. It would be feasible only if the user would have to pay for the extension.
 
https://openai.com/api/pricing/

**Comment by kazuki-sf** [comment]
Thanks @royhadad for asking!
Also, thanks @robertciotoiu for clarifying the technical things!

As OpenAI announced that they will have APIs for ChatGPT soon, I'll think about if I should incorporate this or keep this free. But since my original intention of this extension (open-source code) was to keep it free so let's see.

**Comment by tracure1337** [comment]
@kazuki-sf  why not allow to add an API key if I have one?
